set -g default-terminal "tmux-256color"
set -g escape-time 50

# disable ignorefkeys for rxvt*
# https://github.com/tmux/tmux/issues/3977#issuecomment-2109803704
set -su terminal-features[2]

# fix resetting cursor color (tmux hardcodes Cr; doesn't read from terminfo)
set -as terminal-overrides 'rxvt*:Cr=\E]12;15\a'

set -g base-index 1
setw -g pane-base-index 1

setw -g aggressive-resize on
setw -g window-size largest

set -g message-style bg=black,fg=green,bold
set -g status-style bg=black,fg=yellow
set -g window-status-current-style bold

#set -g pane-border-status top
set -g status-justify centre
set -g status-right ""
#set -g status-right " \"#{=21:pane_title}\" %H:%M %d-%b-%y"

set -g set-titles on
set -g set-titles-string "t[#S] #T"

set -g mouse on
set -g set-clipboard on
set -g focus-events on

# don't enter copy mode when dragging
unbind-key -n MouseDrag1Pane
unbind-key -T copy-mode MouseDrag1Pane

# screen-like bindings
set -g prefix C-a
unbind C-b
bind-key -N "Send prefix"          a   send-prefix
bind-key -N "Select last window"   C-a last-window
bind-key -N "Kill current pane"    K   confirm-before kill-pane
bind-key -N "Kill current session" \\  confirm-before kill-session

# no repeat for pane switching
bind-key -N "Select the pane above the active pane"           Up    select-pane -U
bind-key -N "Select the pane below the active pane"           Down  select-pane -D
bind-key -N "Select the pane to the left of the active pane"  Left  select-pane -L
bind-key -N "Select the pane to the right of the active pane" Right select-pane -R

# new windows in the same directory
bind-key -N "Create a new window"       c  new-window -c "#{pane_current_path}"
bind-key -N "Split window vertically"   \" split-window -c "#{pane_current_path}"
bind-key -N "Split window horizontally" \% split-window -h -c "#{pane_current_path}"

# reload config
bind-key -N "Reload ~/.tmux.conf" R source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
