#!/bin/bash

set -o errexit

if [[ $# -lt 2 ]]; then
    echo 'Usage: git interdiff <commit1> <commit2>'
    exit 1
fi

C1="$1"
C2="$2"
F1=`mktemp --tmpdir tmp.XXXXXXXX.patch`
F2=`mktemp --tmpdir tmp.XXXXXXXX.patch`
trap "rm -f $F1 $F2" EXIT

git show $C1 >$F1
git show $C2 >$F2

vimdiff $F1 $F2
