#!/bin/bash

set -e

if [[ $# -lt 1 ]]; then
    echo 'Usage: git for-each <command> [options...]'
    exit 1
fi

function echo_bold_underline {
	perl -M5.010 -e 'my $s = "##### " . shift; my $t1 = `tput bold; tput smul`; my $t2 = `tput sgr0`; my $c = `tput cols`; $s .= " " x ($c - length($s)); say($t1 . $s . $t2);' "$@"
}

find . -maxdepth 2 -name .git | while read f; do echo_bold_underline "$f"; git -C "${f%/.git}" "$@"; echo; done
