#!/bin/bash
if [ "$#" != "1" ]; then
    echo "Usage: git rsync-new xxx.getgooddata.com:/opt"
    exit 1
fi

cd `git rev-parse --git-dir`/..
rsync -avzR `git cherry origin/master | awk '{ print \$2 }' | xargs git-list-changed-files` $1
