#!/usr/bin/perl

use Encode;
use MIME::Base64;
use Regexp::Common qw /URI/;

sub on_osc_seq {
	my ($term, $op, $args) = @_;
	return () unless $op eq 52;

	my ($clip, $data) = split ';', $args, 2;
	$data = decode('utf8', decode_base64($data));

	$term->selection($data, $clip =~ /c/);
	$term->selection_grab(urxvt::CurrentTime, $clip =~ /c/);

	if ($data =~ m{^$RE{URI}{HTTP}{-scheme => qr/https?/}$}) {
		system("sensible-browser", $data);
	}

	return ();
}
