let &l:path = join([
	\ 'lib',
	\ 'src',
	\ 'apps/*/lib',
	\ 'apps/*/src',
	\ 'deps/*/lib',
	\ 'deps/*/src',
	\ '~/src-elixir/elixir/lib/*/lib',
	\ '~/src-elixir/elixir/lib/*/src',
	\ 'apps/**/lib',
	\ 'apps/**/src',
	\ 'deps/**/lib',
	\ 'deps/**/src',
	\ &g:path,
\ ], ',')
