#!/usr/bin/env node

// workaround for https://github.com/microsoft/playwright/issues/31057
const crPdf = require('/usr/share/nodejs/playwright-core/lib/server/chromium/crPdf.js');
const crPdf_generate = crPdf.CRPDF.prototype.generate;
crPdf.CRPDF.prototype.generate = async function (options) {
	const options2 = {
		...options,
		preferCSSPageSize: true,
	};
	return crPdf_generate.call(this, options2);
};

require('/usr/bin/playwright')
