Host unix/* unix%* vsock/* vsock%* vsock-mux/* vsock-mux%* machine/* machine%*
	VerifyHostKeyDNS no

Host qemu/* qemu:system/* qemu:session/*
	VerifyHostKeyDNS no

	# Disable all kinds of host identity checks, since these addresses are generally ephemeral.
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
