Host *.libvirt
	User vagrant
	ControlMaster auto
	IdentityFile ~/.ssh/id_rsa_vagrant

	# Disable all kinds of host identity checks, since these addresses are generally ephemeral.
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null

# vim:set ft=sshconfig:
