templates:
  params:
    author-name: Tomáš Janoušek
    author-email: tomi@nomi.cz
    copyright: ! 'Copyright: (c) 2024 Tomáš Janoušek'
    github-username: liskin

system-ghc: true
install-ghc: false
# compiler-check: newer-minor

recommend-stack-upgrade: false

build:
  library-profiling: true
  executable-profiling: true
