#!/usr/bin/env bash

set -eu -o pipefail

# avoid concurrent executions
exec {lock_fd}>"/run/liskin-suspend.lock"
flock --nonblock "$lock_fd" || exit

unlocked=
for session in $(loginctl list-sessions --no-legend | awk '{ print $1 }'); do
	if [[ "$(loginctl show-session --property=Remote "$session")" == "Remote=no" && "$(loginctl show-session --property=LockedHint "$session")" == "LockedHint=no" ]]; then
		unlocked=:
	fi
done

if [[ ! $unlocked ]]; then
	if [[ ${1-} == "button" ]]; then
		touch /run/liskin-suspend-button
	fi

	systemctl suspend
else
	loginctl lock-sessions

	if [[ ${1-} == "button" ]]; then
		chvt 1 || :
		sleep 1
		fbset --verbose --geometry 1920 1080 1920 1080 32
	fi
fi
