#!/usr/bin/env bash

set -eu

case "$1" in
	charge)
		for b in /sys/class/power_supply/BAT*; do
			echo 70 > "$b"/charge_start_threshold
			echo 80 > "$b"/charge_stop_threshold
		done
		;;

	normal)
		for b in /sys/class/power_supply/BAT*; do
			echo 40 > "$b"/charge_start_threshold
			echo 80 > "$b"/charge_stop_threshold
		done
		;;

	full-int)
		echo 100 > /sys/class/power_supply/BAT0/charge_stop_threshold
		echo 90 > /sys/class/power_supply/BAT0/charge_start_threshold
		;;

	full-ext)
		echo 100 > /sys/class/power_supply/BAT1/charge_stop_threshold
		echo 90 > /sys/class/power_supply/BAT1/charge_start_threshold
		;;

	full)
		for b in /sys/class/power_supply/BAT*; do
			echo 100 > "$b"/charge_stop_threshold
			echo 90 > "$b"/charge_start_threshold
		done
		;;
esac
