#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe

# avoid concurrent executions
exec {lock_fd}>"/run/liskin-suspend.lock"
flock --nonblock "$lock_fd" || exit

unlocked=$(
	loginctl list-sessions --no-legend \
		| awk '{ print $1 }' \
		| xargs -n1 loginctl show-session --property=LockedHint \
		| grep --invert-match --line-regexp --fixed-strings LockedHint=yes || :
)

if [[ ! $unlocked ]]; then
	systemctl suspend
else
	loginctl lock-sessions

	if [[ ${1-} == "button" ]]; then
		chvt 1 || :
	fi
fi
