#!/usr/bin/env bash

set -eu -o pipefail

# avoid concurrent executions
exec {lock_fd}>"/run/liskin-suspend.lock"
flock --nonblock "$lock_fd" || exit

unlocked=
for session in $(loginctl list-sessions --no-legend | awk '{ print $1 }'); do
	if [[ "$(loginctl show-session --property=VTNr "$session")" != "VTNr=0" && "$(loginctl show-session --property=LockedHint "$session")" == "LockedHint=no" ]]; then
		unlocked=:
	fi
done

if [[ ! $unlocked ]]; then
	if [[ ${1-} == "button" ]]; then
		touch /run/liskin-suspend-button
		/usr/local/sbin/liskin-clear-agents || :
	fi

	# stop fprintd before suspend to prevent the reader getting stuck in a weird state
	systemctl stop fprintd.service || :

	# FIXME: use Inhibitor Locks API instead
	liskin-user-system-sleep pre suspend

	systemctl suspend
else
	loginctl lock-sessions

	if [[ ${1-} == "button" ]]; then
		chvt 1 || :
		sleep 1
		fbset --verbose --geometry 1920 1080 1920 1080 32
	fi
fi
