.PHONY: all
all:

all: gh-actions-cache
gh-actions-cache:
	gh extension install actions/gh-actions-cache

all: gh-markdown-preview
gh-markdown-preview:
	gh extension install yusukebe/gh-markdown-preview

include ~/_gitignore.mk
