.PHONY: all
all:

all: gh-markdown-preview
gh-markdown-preview:
	gh extension install --pin v1.11.0 yusukebe/gh-markdown-preview

all: gh-dash
gh-dash:
	gh extension install --pin v4.23.2 dlvhdr/gh-dash

all: gh-pin-actions
gh-pin-actions:
	gh extension install --pin v0.0.7 amenocal/gh-pin-actions

include ~/_gitignore.mk
