#!bash
# shellcheck disable=SC2239

. /usr/share/bash-completion/completions/git

# shellcheck source-path=../../..
eval "$(
	source "$HOME"/bin/.cachelib
	cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/bash-completion-git-machete" cache_refresh_age=3600 cache \
		git machete completion bash
)"
