#!bash

type -t _completion_cache >/dev/null || source "${BASH_SOURCE[0]%/*}"/../helpers/completion_cache

function _mix_help_names() (
	cd "$1" && mix help --names
)

function _mix {
	local cur prev words cword
	_init_completion || return

	# only complete first argument
	if [[ $cword != 1 ]]; then
		_filedir
		return
	fi

	cache_refresh_age=10 _completion_cache _mix_help_names "$(pwd -P)"
}

complete -F _mix mix
