# see compton.conf

backend = "glx"
vsync = true

unredir-if-possible = true

rules = (
	# disable forced unredir on _NET_WM_BYPASS_COMPOSITOR (breaks xsecurelock)
	{ unredir = true },
)

# vim:set ft=conf:
