#!/usr/bin/env bash

set -eu -o pipefail

: "${1:?}" "${2:?}"

for user in $(loginctl list-users --no-legend | awk '{ print $1 }'); do
	systemd-run \
		--quiet --collect --wait \
		--user --machine "$user"@ \
		bash -c "if [[ -d ~/.local/lib/liskin-system-sleep ]]; then run-parts -v --arg=$(printf %q "$1") --arg=$(printf %q "$2") ~/.local/lib/liskin-system-sleep; fi" || :
done
