#!/usr/bin/env bash

# workaround for the bluetooth adapter blocking s2idle when devices are connected

set -eu -o pipefail

function o { printf -->&2 "%s:%s\\n" "${0##*/}" "$(printf " %q" "$@")"; "$@"; }

function with-devices {
	local dev
	{ busctl tree --list org.bluez || :; } | while read -r dev; do
		if [[ $dev == /org/bluez/*/dev_??_??_??_??_??_?? ]]; then
			"$1" "$dev" "${@:2}"
		fi
	done
}

function if-connected {
	local dev; dev=${1:?}; shift
	local connected
	connected=$(busctl get-property -j org.bluez "$dev" org.bluez.Device1 Connected | jq -r .data) || connected=false
	if [[ $connected == true ]]; then
		"$1" "$dev" "${@:2}"
	fi
}

function disconnect {
	o busctl call org.bluez "${1:?}" org.bluez.Device1 Disconnect || :
}

function disconnect-all {
	with-devices if-connected disconnect
}

case "$1" in
	pre) disconnect-all ;;
esac
