resolver: lts-21.21

packages:
    - X11
    - X11-xft
    - arbtt
    - fourmolu
    - ghcid
    - implicit-hie
    - xmobar
    - xmonad
    - xmonad-contrib

extra-deps:
    - bytestring-progress-1.4

flags:
    xmobar:
        with_xft: true
        with_threaded: true
    xmonad-contrib:
        use_xft: true
    bytestring-progress:
        use-system-progressbar: false

ghc-options:
    xmonad-contrib: '-j'
