#!/usr/bin/env bash

set -eu

: "${IFACE:?}"
: "${MODE:?}"

if [[ "$MODE" == "start" ]]; then
	if [[ "$IFACE" == @("bnep0") ]]; then
		/usr/local/sbin/liskin-vpn-route up "$IFACE"
	fi
elif [[ "$MODE" == "stop" ]]; then
	/usr/local/sbin/liskin-vpn-route down
fi
