[settings]
experimental = true
not_found_auto_install = false
paranoid = true

[settings.status]
missing_tools = "always"
show_env = true

[tools]
"cargo:ast-grep" = "0.17.1"
"cargo:cargo-audit" = "0.18.3"
"cargo:cargo-cache" = "0.8.3"
"cargo:cargo-edit" = "0.12.2"
"cargo:cargo-watch" = "8.5.2"
"cargo:ripgrep_all" = "0.10.6"
"cargo:tokio-console" = "0.1.9"
"cargo:watchexec-cli" = "1.25.1"
"ubi:YodaEmbedding/frece" = "v1.0.6"
"ubi:cargo-bins/cargo-binstall" = "v1.10.5"
usage = "0.3.1"
