[settings]
experimental = true
not_found_auto_install = false
paranoid = true
pin = true
pipx_uvx = true
trusted_config_paths = ['~/.config/mise/config.toml']

[settings.status]
missing_tools = "always"
show_env = true

[tools]
"cargo:JojiiOfficial/LiveBudsCli" = "rev:4a2d75f5bede545738110dccbac033954b1d6087"
"cargo:ast-grep" = "0.27.3"
"cargo:cargo-audit" = "0.20.1"
"cargo:cargo-cache" = "0.8.3"
"cargo:cargo-edit" = "0.13.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:ripgrep_all" = "0.10.6"
"cargo:tokio-console" = "0.1.12"
"cargo:watchexec-cli" = "2.1.2"
"npm:prettier" = "3.3.3"
"npm:typescript-language-server" = "4.3.3"
"pipx:gdbgui" = "0.15.2.0"
"pipx:git-when-merged" = "1.2.1"
"pipx:liskin/foursquare-swarm-ical" = "172e1d0336fdab568ab6b5ed505a06daafa5078c"
"pipx:liskin/liscopridge" = "a9c2debe41d045ef184c87bbad331ee6fa20b13c"
"pipx:liskin/strava-gear" = "6883fefc8a8f0a2e5144f271480e406a33540417"
"pipx:liskin/strava-offline" = "1abe986b2d1ba6a300954df6ff648d88bead6c80"
"pipx:markdown2ctags" = "0.3.3"
"pipx:pandoc-plantuml-filter" = "0.1.5"
"pipx:pushl" = "0.3.5"
"pipx:python-dxf" = "12.1.0"
"pipx:timezonefinder" = "6.5.3"
"ubi:YodaEmbedding/frece" = "v1.0.6"
"ubi:astral-sh/uv" = "0.4.18"
"ubi:cargo-bins/cargo-binstall" = "v1.10.6"
"ubi:evcxr/evcxr" = "v0.17.0"
"ubi:hadolint/hadolint" = "v2.12.0"
"ubi:kubernetes-sigs/kind" = "v0.22.0"
"ubi:oz/tz" = "v0.7.0"
"ubi:pkolaczk/fclones" = "v0.34.0"
"ubi:rust-analyzer/rust-analyzer" = "2024-09-16"
"ubi:tamasfe/taplo" = "0.9.3"
"ubi:tilt-dev/ctlptl" = "v0.8.32"
"ubi:tilt-dev/tilt" = "v0.33.19"
"ubi:wagoodman/dive" = "v0.12.0"
usage = "0.8.4"
