[settings]
not_found_auto_install = false
paranoid = true
pin = true
trusted_config_paths = ['~/.config/mise/config.toml']
idiomatic_version_file_enable_tools = []

[settings.status]
missing_tools = "always"
show_env = true

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "pnpm"

[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.111"
"cargo:JojiiOfficial/LiveBudsCli" = "rev:4a2d75f5bede545738110dccbac033954b1d6087"
"cargo:YodaEmbedding/frece" = "rev:d4071c6c852e68dda82b7ab0bfb0f141b39d4484"
"cargo:cargo-audit" = "0.22.0"
"cargo:cargo-deny" = "0.18.5"
"cargo:cargo-edit" = "0.13.7"
"cargo:cargo-machete" = "0.9.1"
"cargo:cargo-semver-checks" = "0.45.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:evcxr_repl" = "0.21.1"
"cargo:fclones" = "0.35.0"
"cargo:mergiraf" = "0.16.1"
"cargo:ripgrep_all" = "0.10.10"
"cargo:tokio-console" = "0.1.14"
"npm:@mermaid-js/mermaid-cli" = "11.9.0"
"npm:prettier" = "3.6.2"
"npm:typescript-language-server" = "4.4.0"
"npm:yaml-language-server" = "1.18.0"
"pipx:gdbgui" = "0.15.3.0"
"pipx:git-when-merged" = "1.2.1"
"pipx:liskin/foursquare-swarm-ical" = "172e1d0336fdab568ab6b5ed505a06daafa5078c"
"pipx:liskin/liscopridge" = "a9c2debe41d045ef184c87bbad331ee6fa20b13c"
"pipx:liskin/strava-gear" = "6883fefc8a8f0a2e5144f271480e406a33540417"
"pipx:liskin/strava-offline" = "1abe986b2d1ba6a300954df6ff648d88bead6c80"
"pipx:markdown2ctags" = "0.3.3"
"pipx:pandoc-plantuml-filter" = "0.1.5"
"pipx:proselint" = "0.16.0"
"pipx:pushl" = "0.4.0"
"pipx:python-dxf" = "12.1.1"
"pipx:timezonefinder" = "8.0.0"
"ubi:ankitpokhrel/jira-cli" = { version = "1.7.0", exe = "jira" }
"ubi:chrishrb/go-grip" = "0.5.6"
"ubi:oz/tz" = "0.8.0"
ast-grep = "0.39.9"
buildifier = "8.2.1"
cargo-binstall = "1.17.4"
difftastic = "0.65.0"
dive = "0.13.1"
docker-buildx = "0.29.1"
docker-compose = "2.40.3"
editorconfig-checker = "3.4.1"
gh = "2.86.0"
hadolint = "2.14.0"
lua-language-server = "3.16.4"
mprocs = "0.7.3"
neovim = "0.11.6"
pandoc = "3.5"
pnpm = "10.29.3"
regctl = "0.10.0"
rust-analyzer = "2026-02-16"
stylua = "2.3.1"
taplo = "0.10.0"
tilt = "0.35.2"
usage = "2.17.0"
uv = "0.10.3"
watchexec = "2.3.2"

[tool_alias]
docker-buildx = "github:docker/buildx[bin=docker-cli-plugin-docker-buildx]"
